-- Итоговый скрипт создания БД — финальная схема (всё создаётся сразу)

-- Устанавливаем кодировку и настройки
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- =======================
-- Создание ENUM-типов
-- =======================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('user', 'editor', 'admin', 'moderator', 'staff');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'publication_type') THEN
    CREATE TYPE publication_type AS ENUM ('article', 'news');
  END IF;
END$$;

-- =======================
-- Таблица users
-- =======================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role user_role NOT NULL DEFAULT 'user',
  bio TEXT,
  avatar_url TEXT DEFAULT '/img/default-avatar.jpg',
  rated_games INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- =======================
-- Таблица games
-- =======================
CREATE TABLE IF NOT EXISTS games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  developers TEXT[],         -- массив разработчиков
  publishers TEXT[],         -- массив издателей
  slug VARCHAR(100),
  release_date DATE,
  rating NUMERIC(3,2) DEFAULT 0, -- точный рейтинг
  background_image TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_games_title ON games(title);
CREATE INDEX IF NOT EXISTS idx_games_slug ON games(slug);
CREATE INDEX IF NOT EXISTS idx_games_rating ON games(rating DESC);
CREATE INDEX IF NOT EXISTS idx_games_release_date ON games(release_date DESC);

-- =======================
-- Таблица genres и связь game_genres
-- =======================
CREATE TABLE IF NOT EXISTS genres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS game_genres (
  game_id BIGINT NOT NULL,
  genre_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (game_id, genre_id),
  CONSTRAINT fk_game_genres_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_game_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_game_genres_game_id ON game_genres(game_id);
CREATE INDEX IF NOT EXISTS idx_game_genres_genre_id ON game_genres(genre_id);

-- =======================
-- Скриншоты
-- =======================
CREATE TABLE IF NOT EXISTS screenshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT fk_screenshots_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_screenshots_game_id ON screenshots(game_id);

-- =======================
-- Таблица publications
-- =======================
CREATE TABLE IF NOT EXISTS publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  game_id BIGINT,
  image VARCHAR(255),
  type publication_type NOT NULL,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT fk_publications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_publications_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_publications_user_id ON publications(user_id);
CREATE INDEX IF NOT EXISTS idx_publications_game_id ON publications(game_id);
CREATE INDEX IF NOT EXISTS idx_publications_type ON publications(type);
CREATE INDEX IF NOT EXISTS idx_publications_created_at ON publications(created_at DESC);

-- =======================
-- Таблица reviews
-- =======================
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  game_id BIGINT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  content TEXT NOT NULL,
  is_edited BOOLEAN DEFAULT FALSE,
  likes INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_reviews_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT uq_reviews_user_game UNIQUE (user_id, game_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_game_id ON reviews(game_id);
CREATE INDEX IF NOT EXISTS idx_reviews_rating ON reviews(rating);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews(created_at DESC);

-- =======================
-- Таблица favorites (пользователь — игра)
-- =======================
CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  game_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT uq_favorites_user_game UNIQUE (user_id, game_id),
  CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_favorites_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_game_id ON favorites(game_id);

-- =======================
-- Таблица favorites_genres
-- =======================
CREATE TABLE IF NOT EXISTS favorites_genres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  genre_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT uq_favorites_genres_user_genre UNIQUE (user_id, genre_id),
  CONSTRAINT fk_favorites_genres_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_favorites_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_favorites_genres_user_id ON favorites_genres(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_genres_genre_id ON favorites_genres(genre_id);

-- =======================
-- Лайки публикаций и просмотры
-- =======================
CREATE TABLE IF NOT EXISTS publication_likes (
  user_id BIGINT NOT NULL,
  publication_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, publication_id),
  CONSTRAINT fk_pub_likes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_pub_likes_pub FOREIGN KEY (publication_id) REFERENCES publications(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS publication_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_id BIGINT NOT NULL,
  user_id BIGINT,
  ip_address VARCHAR(45),
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT fk_pub_views_pub FOREIGN KEY (publication_id) REFERENCES publications(id) ON DELETE CASCADE,
  CONSTRAINT fk_pub_views_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pub_views_check ON publication_views(publication_id, user_id, ip_address);

-- =======================
-- Таблица comments и likes для комментариев
-- =======================
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  publication_id BIGINT NOT NULL,
  parent_id BIGINT,
  content TEXT NOT NULL,
  likes INTEGER DEFAULT 0,
  is_edited BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_publication FOREIGN KEY (publication_id) REFERENCES publications(id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_publication_id ON comments(publication_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);

CREATE TABLE IF NOT EXISTS comment_likes (
  user_id BIGINT NOT NULL,
  comment_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, comment_id),
  CONSTRAINT fk_comment_likes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

-- =======================
-- Таблицы для кодов восстановления/смены почты
-- =======================
CREATE TABLE IF NOT EXISTS password_reset_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  code VARCHAR(6) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_password_reset_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_password_reset_user_id ON password_reset_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_expires_at ON password_reset_codes(expires_at);

CREATE TABLE IF NOT EXISTS email_change_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  old_email VARCHAR(100) NOT NULL,
  verification_code VARCHAR(6) NOT NULL,
  new_email VARCHAR(100),
  new_email_code VARCHAR(6),
  step VARCHAR(20) NOT NULL DEFAULT 'verify_old',
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_email_change_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_email_change_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_email_change_user_id ON email_change_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_email_change_expires_at ON email_change_codes(expires_at);

-- =======================
-- Вспомогательные функции и триггеры
-- =======================

-- Функция обновления updated_at для BEFORE UPDATE триггеров
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Подключаем BEFORE UPDATE триггеры для таблиц, где есть updated_at
DROP TRIGGER IF EXISTS update_games_updated_at ON games;
CREATE TRIGGER update_games_updated_at
BEFORE UPDATE ON games
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_reviews_updated_at ON reviews;
CREATE TRIGGER update_reviews_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_publications_updated_at ON publications;
CREATE TRIGGER update_publications_updated_at
BEFORE UPDATE ON publications
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_comments_updated_at ON comments;
CREATE TRIGGER update_comments_updated_at
BEFORE UPDATE ON comments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Функция для обновления рейтинга игры и счётчика rated_games пользователя
CREATE OR REPLACE FUNCTION update_game_rating()
RETURNS TRIGGER AS $$
DECLARE
  target_game_id BIGINT;
  avg_rating NUMERIC(3,2);
BEGIN
  IF (TG_OP = 'DELETE') THEN
    target_game_id := OLD.game_id;
  ELSE
    target_game_id := NEW.game_id;
  END IF;

  SELECT COALESCE(AVG(rating), 0) INTO avg_rating
  FROM reviews
  WHERE game_id = target_game_id;

  UPDATE games
  SET rating = ROUND(avg_rating::numeric, 2),
      updated_at = NOW()
  WHERE id = target_game_id;

  IF (TG_OP = 'INSERT') THEN
    UPDATE users SET rated_games = rated_games + 1 WHERE id = NEW.user_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE users SET rated_games = GREATEST(rated_games - 1, 0) WHERE id = OLD.user_id;
  ELSIF (TG_OP = 'UPDATE') THEN
    -- Для обновления рейтинга при изменении оценки, количество rated_games не меняется.
    NULL;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Удаляем старые триггеры (если были) и создаём новые
DROP TRIGGER IF EXISTS update_game_rating_on_insert ON reviews;
DROP TRIGGER IF EXISTS update_game_rating_on_update ON reviews;
DROP TRIGGER IF EXISTS update_game_rating_on_delete ON reviews;

CREATE TRIGGER update_game_rating_on_insert
AFTER INSERT ON reviews
FOR EACH ROW
EXECUTE FUNCTION update_game_rating();

CREATE TRIGGER update_game_rating_on_update
AFTER UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION update_game_rating();

CREATE TRIGGER update_game_rating_on_delete
AFTER DELETE ON reviews
FOR EACH ROW
EXECUTE FUNCTION update_game_rating();

-- Функция для получения средней оценки игры
CREATE OR REPLACE FUNCTION get_game_avg_rating(game_id_param BIGINT)
RETURNS NUMERIC(3,2) AS $$
DECLARE
  avg_rating NUMERIC(3,2);
BEGIN
  SELECT COALESCE(ROUND(AVG(rating), 2), 0) INTO avg_rating
  FROM reviews
  WHERE game_id = game_id_param;

  RETURN avg_rating;
END;
$$ LANGUAGE plpgsql;

-- Функция для получения статистики по оценкам игры
CREATE OR REPLACE FUNCTION get_game_stats(game_id_param BIGINT)
RETURNS TABLE (
  total_reviews BIGINT,
  avg_rating NUMERIC(3,2),
  five_stars BIGINT,
  four_stars BIGINT,
  three_stars BIGINT,
  two_stars BIGINT,
  one_star BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*) AS total_reviews,
    COALESCE(ROUND(AVG(rating), 2), 0) AS avg_rating,
    COUNT(CASE WHEN rating = 5 THEN 1 END) AS five_stars,
    COUNT(CASE WHEN rating = 4 THEN 1 END) AS four_stars,
    COUNT(CASE WHEN rating = 3 THEN 1 END) AS three_stars,
    COUNT(CASE WHEN rating = 2 THEN 1 END) AS two_stars,
    COUNT(CASE WHEN rating = 1 THEN 1 END) AS one_star
  FROM reviews
  WHERE game_id = game_id_param
  GROUP BY game_id;
END;
$$ LANGUAGE plpgsql;

-- Функция для массового обновления рейтингов (для миграций/инициализации)
CREATE OR REPLACE FUNCTION update_all_games_ratings()
RETURNS VOID AS $$
BEGIN
  UPDATE games g
  SET rating = COALESCE(
      (SELECT ROUND(AVG(r.rating), 2)
       FROM reviews r
       WHERE r.game_id = g.id
       GROUP BY r.game_id),
      0
    ),
    updated_at = NOW()
  WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.game_id = g.id);

  RAISE NOTICE 'Обновлены рейтинги всех игр';
END;
$$ LANGUAGE plpgsql;

-- Вызываем функцию для инициализации рейтингов (если нужно)
SELECT update_all_games_ratings();

-- =======================
-- Сообщение о завершении создания схемы
-- =======================
DO $$
BEGIN
  RAISE NOTICE '=========================================';
  RAISE NOTICE 'Создание схемы завершено: финальная структура базы данных готова.';
  RAISE NOTICE 'Созданы типы, таблицы, индексы, функции и триггеры.';
  RAISE NOTICE '=========================================';
END $$;
